### ISSUE TITLE
[Proposal] Some PSR-4 Goodness

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#1]
I would like to contribute a little bit, and was wondering if I could start by introducing Composer support, and renaming the source folder to `src`. Would you welcome such a change?

**Comment by HallofFamer** [comment]
Of course I do not mind. I like PSR-4 standard too, so please do as you want to. Thank you so much for your interest and comment. 

It seems that Github messes up with the indentation since its default tab size is 8 while I use 4 spaces. I do not have a clue how to fix as of now though, except for manually editing all source code to indent each line. Let me know too if you know how to fix it.

**Comment by assertchris** [comment]
I will make a separate proposal to fix the PSR-2 stuff. It's relatively straightforward. :)

**Comment by HallofFamer** [comment]
Alright sounds good, I very appreciate your contribution. I really hope the Collection Framework will help with more people using it. And if I may ask, are the the author of Pro PHP MVC?
http://www.amazon.com/Pro-Experts-Voice-Open-Source/dp/1430241640/ref=sr_1_1?ie=UTF8&qid=1422811486&sr=8-1&keywords=pro+php+mvc

**Comment by assertchris** [comment]
I am the author of that horrible book. :D

**Comment by HallofFamer** [comment]
@assertchris: I see. XD I think the book was very good, as it did help me a lot 2 years ago. I think the fact is that it assumed that each reader already had a very solid foundation of PHP and OOP, while many who purchased the book did not and ended up getting confused. For me, it was understandable though, and I'd recommend people to buy it. 

Anyway, thank you so much for your participation, and please let me know if there's anything else that needs to be done to make the code clean and easier to read. I am very glad to listen.

**Comment by assertchris** [comment]
Thanks. :)

Well as soon as you are happy with the PSR-4 pull request, and that's merged; I can start on the PSR-2 formatting changes...

**Comment by HallofFamer** [comment]
You are very welcome. And yeah I like what it is there so far, are you completely done with PSR-4 pull request? If so, we will merge the pull request.

**Comment by assertchris** [comment]
I am done with it. The demos are all working, which means the autoloading is working as expected. :)

**Comment by HallofFamer** [comment]
It has been merged, thank you for your contribution. It's shaping up pretty well now.

**Comment by assertchris** [comment]
:+1:
