### ISSUE TITLE
[Proposal] Some PSR-2 Goodness

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#2]
Hey! After the [PSR-4 stuff](https://github.com/HallofFamer/PHP-Collections-Framework/issues/1), I would like to do some easy PSR-2 fixes. It won't change the function of the code - merely the format.

**Comment by HallofFamer** [comment]
It seems that PSR-4 is done now, the package can now be installed through composer. its about time to get through PSR-2, thanks for the proposal.

**Comment by assertchris** [comment]
:+1:

**Comment by assertchris** [comment]
Woah! I forgot which issue this was :D

**Comment by HallofFamer** [comment]
I see you made another pull request and the formatting has been fixed. Are you done 100% with the new pull request? If so, I will merge it.

**Comment by assertchris** [comment]
It was done with a combination of PHPStorm macros and [php-cs-fixer](https://packagist.org/packages/fabpot/php-cs-fixer). All of the examples are working nicely, so I'm done with the automated stuff (this PR). 

Next I would like to work on individual classes, adding tests for them. Separate issues!

**Comment by HallofFamer** [comment]
Alright, I understand. I will merge the pull requests then. And yeah there are more work to do with PCF, but as you said it would be a different issue. You can open another issue when you feel necessary then, thanks again.

**Comment by assertchris** [comment]
:+1:
