### ISSUE TITLE
[Proposal] Remove Native\Objective

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#27]
I've been studying how `Native\Objective` is used and I think it would be better to split it up, and implement most of interface methods in `Native\Object`. I've created the following interfaces:

- https://github.com/HallofFamer/PHP-Collections-Framework/pull/17
- https://github.com/HallofFamer/PHP-Collections-Framework/pull/18
- https://github.com/HallofFamer/PHP-Collections-Framework/pull/19
- https://github.com/HallofFamer/PHP-Collections-Framework/pull/20
- https://github.com/HallofFamer/PHP-Collections-Framework/pull/21

I also want to move the `equals` method into `Utilities\Comparable`. Lastly I would like to move all `*able` interfaces into the root [`src`] folder, as their various methods are expected about 830 times in `Collections\*`.

**Comment by HallofFamer** [comment]
I will have to think about this. The reason why Objective interface exists is that it provides an interface for classes extending from PHP's built-in classes to be used in collection, as these classes cannot inherit from the root Object class. For instance, the Arrays class(which extends SplFixedArray) and custom exception classes inheriting PHP's built-in classes. If Objective is removed, these classes will not be usable in collections. Lemme know further what you think about this.
