### ISSUE TITLE
[Proposal] Simplify Doc Comments

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#31]
I think we could reasonably remove a few of the annotation types:

1. `@final`, `@access` and `@abstract` can be inferred.
2. `@copyright` and `@link` can be clearly represented in the readme.
3. `@category` and `@package` provide no value for static analysis or documentation.

Would you be ok with me removing these?

**Comment by HallofFamer** [comment]
Yeah I am okay with that, no problem.

**Comment by assertchris** [comment]
Related: if this library is used in a game, then perhaps you can advertise the game a little in the readme. As opposed to the `@link` annotations...

**Comment by HallofFamer** [comment]
yeah of course, I do write a browser game script, so it is a good idea.

**Comment by assertchris** [comment]
https://github.com/HallofFamer/PHP-Collections-Framework/pull/36

**Comment by assertchris** [comment]
Will apply to collection types in due course.
