### ISSUE TITLE
[Proposal] Pick A Method Style

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#34]
So I've been adding some [interfaces with aliases](https://github.com/HallofFamer/PHP-Collections-Framework/blob/a9e9dfb96bcfbda6ccbdfaba5b60826c97a6093d/src/Stringable.php#L26-L42). I think my indecision is bad. Perhaps we should be picking a single style for this stuff and allow add-on projects to inject the other style.

The options are:

```php
$type->getValue();
$type->toInteger();
$type->toIntegerValue();
$type->getSlice();

// vs.

$type->value();
$type->integer();
$type->integerValue();
$type->slice();
```

I like the second style more, as it makes it more difficult to design sane mutable interfaces. By extension, I am a huge fan of immutable types. Right now the style is mostly immutable, but with a mixture of these method name styles.

What do you think?

**Comment by HallofFamer** [comment]
yeah I think the second style is better too.

**Comment by assertchris** [comment]
I would like to standardise this change across the native types, and then the collection types [when I get around to them]. I'll suggest a way to create the add-on package(s) to allow the first style.

**Comment by HallofFamer** [comment]
Alright, sounds like a plan. Will you post a new issue regarding the add-on package(s) or continue to use this one?

**Comment by assertchris** [comment]
New issue I think. This one is more about changing the existing behaviour...

**Comment by assertchris** [comment]
https://github.com/HallofFamer/PHP-Collections-Framework/pull/38

**Comment by assertchris** [comment]
Will apply to collection types in due course.
