### ISSUE TITLE
[Proposal] Some Testing Goodness

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#5]
I would like to add some unit tests. I suggest I tackle 1 class at a time, fixing doc block/syntax/semantic issues, and writing tests for it at the same time. I prefer PHPUnit for this sort of thing. If you would like me to use something else, that would also be fine.

**Comment by HallofFamer** [comment]
I like this idea, 1 class at a time seems to be good and feasible approch. And yeah PHPUnit is the industry standard, and is preferably used here. Lemme know if there's something else you want to bring up and discuss.

**Comment by assertchris** [comment]
Great, I'll get started!

**Comment by HallofFamer** [comment]
Thanks, I very appreciate your help, Chris.

**Comment by assertchris** [comment]
You're welcome :)
