### ISSUE TITLE
[Proposal] Submit to LEOP

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#6]
I think it would be a good idea to submit this library to [LOEP](http://thephpleague.com), once we've worked on it a bit more. There are some requirements (like test coverage) and the namespace changes. You remain in full ownership and control of the library. 

Some benefits for you:

- You are not alone. Other folks [like me] step in to help you make this awesome. When you are on holiday, we help sort out things like issues and pull requests. If you want to take a break from it, someone will pick up the slack.
- You get tons of exposure. The league is becoming a place where developers go when they are looking for good libraries. I think this is a good library and I would like to see it gain more traction.

I would be glad to submit it, on your behalf, after we've worked on some tests. The choice is completely up to you. Think about it! :D

**Comment by HallofFamer** [comment]
I see, this sounds like a very brilliant idea. I'd definitely be very glad if it appears on LOEP after it has been improved to meet LOEP's standard. And of course, I'd love to get to know some more expert developers like you, it will be awesome. Yeah, so let's do it when you feel PCF is ready to be submitted to LOEP, I am all in for it.

**Comment by assertchris** [comment]
I'll leave this open as a reminder.

On an unrelated note - would you mind if I emailed you something? I want to give you a copy of a book I've written [about this very library]!

**Comment by HallofFamer** [comment]
Sounds like a good idea, I hope PCF will help more people using it. 

And of course I dont mind, please send me that. I'd definitely love to have a look!

**Comment by assertchris** [comment]
Is your email address still worldoffame@hotmail.com?

**Comment by HallofFamer** [comment]
yup, this is my email address.

**Comment by assertchris** [comment]
https://github.com/HallofFamer/PHP-Collections-Framework/issues/43
