### ISSUE TITLE
[Proposal] Add Scrutinizer-CI Support

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#8]
It's free for open-source projects (like this one) and provides excellent feedback!

[scrutinizer-ci.com](https://scrutinizer-ci.com)

I can create the appropriate config file, but you'll need to add it to a Scrutinizer account [as only you have the relevant permissions for the repo].

**Comment by HallofFamer** [comment]
Its a good idea too, I just looked at it and seems that I can log in with github account. I will see what I can do with it.

**Comment by assertchris** [comment]
:+1:
