### ISSUE TITLE
[Proposal] Add Travis-CI Support

### ISSUE THREAD

**Issue by assertchris** [HallofFamer/PHP-Collections-Framework#9]
It's free for open-source projects (like this one) and provides excellent feedback!

[travis-ci.org](https://travis-ci.org)

I can create the appropriate config file, but you'll need to add it to a Travis account [as only you have the relevant permissions for the repo].

**Comment by HallofFamer** [comment]
I like it too, I just synchronized Github account and packages with Travis-CI, it seems fast and convenient. I will look at it more later to learn some information about it.

**Comment by assertchris** [comment]
:+1:
